In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import metrics
from sklearn import model_selection
from sklearn import preprocessing
from sklearn import tree
from sklearn import ensemble
import xgboost
np.random.seed(7)

In [109]:
data = pd.read_csv("preprocessed_data.csv",index_col=0)

In [110]:
data.head()

,Bachelor's,Intermediate,Master's,Matric,PhD,Finance,Science,Business,Computer Science,Arts,...,Marketing,Tally ERP,AWS Certified,Mental Health Basics,Digital Marketing,CFA Level 1,Creative Writing,Google Data Analytics,CGPA/Percentage,Recommended Career
0,1,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,67,Business Analyst
1,0,1,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,67,Software Engineer
2,0,0,1,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,90,Financial Analyst
3,1,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,75,Clerk
4,0,0,0,1,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,83,Sales Assistant

In [112]:
target_name = 'Recommended Career'

In [129]:
x = data.drop(labels = [target], axis=1)
x

,Bachelor's,Intermediate,Master's,Matric,PhD,Finance,Science,Business,Computer Science,Arts,...,Python,Marketing,Tally ERP,AWS Certified,Mental Health Basics,Digital Marketing,CFA Level 1,Creative Writing,Google Data Analytics,CGPA/Percentage
0,1,0,0,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,67
1,0,1,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,0,67
2,0,0,1,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,90
3,1,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,75
4,0,0,0,1,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,0,0,0,1,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,90
4996,0,0,1,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,1,0,92
4997,0,0,0,1,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,63
4998,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,83
4999,0,0,1,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,67

In [130]:
target_names = data[target].unique()

y = data[target]

label_encoder = preprocessing.LabelEncoder()
y_encoded = label_encoder.fit_transform( data[target] )

y_encoded

array([ 0, 11,  3, ...,  3, 11,  1], shape=(5000,))

In [131]:
x_trainval, x_test, y_trainval, y_test = model_selection.train_test_split(x, y_encoded, test_size=0.33, stratify=y_encoded, random_state = 7)

In [132]:
x_train, x_val, y_train, y_val = model_selection.train_test_split(x_trainval, y_trainval, test_size=0.2, stratify=y_trainval, random_state = 7)
scaler = preprocessing.StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_val = scaler.transform(x_val)

In [133]:
scaler = preprocessing.StandardScaler()
scaler.fit(x_trainval)
x_trainval = scaler.transform(x_trainval)
x_test = scaler.transform(x_test)

In [134]:
def train_and_evaluate(model, x_train, y_train, x_val, y_val):
    model.fit(x_train, y_train)

    return model.score(x_val, y_val)

In [135]:
number_of_estimators = np.arange(10, 110, 10)
number_of_estimators

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [136]:
max_depths = np.arange(5, 55, 5)
max_depths

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [138]:
optimal_number_of_estimators = number_of_estimators[0]
optimal_depth = max_depths[0]
optimal_accuracy = 0

for num in number_of_estimators:
    for depth in max_depths:
        model = ensemble.RandomForestClassifier(num, max_depth=depth, random_state=7)
        score = train_and_evaluate(model, x_train, y_train, x_val, y_val)
        
        if score > optimal_accuracy:
            optimal_accuracy = score
            optimal_number_of_estimators = num
            optimal_depth = depth

print(optimal_number_of_estimators, optimal_depth, optimal_accuracy)

30 30 0.10895522388059702

In [139]:
number_of_estimators = np.arange(optimal_number_of_estimators-9, optimal_number_of_estimators+11, 2)
number_of_estimators

max_depths = np.arange(optimal_depth-4, optimal_depth+6, 1)
max_depths

for num in number_of_estimators:
    for depth in max_depths:
        model = ensemble.RandomForestClassifier(num, max_depth=depth, random_state=7)
        score = train_and_evaluate(model, x_train, y_train, x_val, y_val)
        
        if score > optimal_accuracy:
            optimal_accuracy = score
            optimal_number_of_estimators = num
            optimal_depth = depth

print(optimal_number_of_estimators, optimal_depth, optimal_accuracy)

35 26 0.11343283582089553

In [140]:
model = ensemble.RandomForestClassifier(optimal_number_of_estimators, max_depth=optimal_depth, random_state=7)

In [141]:
model.fit(x_trainval, y_trainval)

RandomForestClassifier(max_depth=np.int64(26), n_estimators=np.int64(35),
                       random_state=7)

In [142]:
y_test_predicted = model.predict(x_test)
y_test_predicted

array([10,  1,  0, ...,  0,  3, 10], shape=(1650,))

In [143]:
y_test_predicted_strings = label_encoder.inverse_transform(y_test_predicted)
y_test_predicted_strings

array(['School Counselor', 'Clerk', 'Business Analyst', ...,
       'Business Analyst', 'Financial Analyst', 'School Counselor'],
      shape=(1650,), dtype=object)

In [144]:
model.score(x_trainval, y_trainval)

0.9982089552238806

In [145]:
model.score(x_test, y_test)

0.08242424242424243

In [146]:
metrics.confusion_matrix(y_test, y_test_predicted)

array([[12, 15, 10, 13, 10, 12, 11,  8,  9, 12, 11,  7],
       [13, 16,  7, 15, 18, 11, 13, 11,  7,  8, 13, 11],
       [10, 22, 10, 10, 12, 16, 11,  7,  7,  9, 12, 10],
       [16, 15, 20, 11, 11,  8, 10,  9,  4,  9, 14,  9],
       [15, 10, 14, 16,  8, 11, 11,  7,  7, 11, 13, 13],
       [11, 14, 16, 10,  7, 14, 17, 12, 10, 11, 12,  8],
       [20, 11, 19,  9, 10, 15, 13,  8,  7, 17,  7,  7],
       [ 9, 24, 12,  3,  8,  9, 14,  9, 13, 14, 13,  6],
       [14, 16,  6, 13, 13, 18, 10,  8, 10,  7, 12, 11],
       [11, 12, 15, 10, 11,  7, 15, 10, 13, 12,  8, 12],
       [13, 14, 16, 14,  9, 10, 15, 11,  9,  6, 12,  9],
       [ 8, 19, 19,  4, 11, 13, 12, 11, 10, 10, 12,  9]])

In [147]:
print(metrics.classification_report(y_test, y_test_predicted))

              precision    recall  f1-score   support

           0       0.08      0.09      0.09       130
           1       0.09      0.11      0.10       143
           2       0.06      0.07      0.07       136
           3       0.09      0.08      0.08       136
           4       0.06      0.06      0.06       136
           5       0.10      0.10      0.10       142
           6       0.09      0.09      0.09       143
           7       0.08      0.07      0.07       134
           8       0.09      0.07      0.08       138
           9       0.10      0.09      0.09       136
          10       0.09      0.09      0.09       138
          11       0.08      0.07      0.07       138

    accuracy                           0.08      1650
   macro avg       0.08      0.08      0.08      1650
weighted avg       0.08      0.08      0.08      1650

In [149]:
number_of_estimators = np.arange(50, 150, 10)

max_depths = np.arange(5, 25, 2)

optimal_number_of_estimators = number_of_estimators[0]
optimal_depth = max_depths[0]
optimal_accuracy = 0

for num in number_of_estimators:
    for depth in max_depths:
        model = ensemble.AdaBoostClassifier(estimator=tree.DecisionTreeClassifier(max_depth=depth), n_estimators=num, random_state=7)
        score = train_and_evaluate(model, x_train, y_train, x_val, y_val)
        
        if score > optimal_accuracy:
            optimal_accuracy = score
            optimal_number_of_estimators = num
            optimal_depth = depth

print(optimal_number_of_estimators, optimal_depth, optimal_accuracy)

/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

120 13 0.10895522388059702

In [150]:
model = ensemble.AdaBoostClassifier(estimator=tree.DecisionTreeClassifier(max_depth=optimal_depth), n_estimators=optimal_number_of_estimators, random_state=7)

In [151]:
model.fit(x_trainval, y_trainval)

/home/tsone/venvs/ml/lib/python3.14/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=np.int64(13)),
                   n_estimators=np.int64(120), random_state=7)

In [152]:
y_test_predicted = model.predict(x_test)
y_test_predicted

array([5, 7, 6, ..., 2, 3, 7], shape=(1650,))

In [153]:
model.score(x_train, y_train)

0.9981343283582089

In [154]:
model.score(x_test, y_test)

0.0703030303030303

In [155]:
print(metrics.classification_report(y_test, y_test_predicted))

              precision    recall  f1-score   support

           0       0.07      0.06      0.07       130
           1       0.07      0.10      0.08       143
           2       0.05      0.06      0.05       136
           3       0.08      0.07      0.08       136
           4       0.08      0.07      0.07       136
           5       0.12      0.12      0.12       142
           6       0.07      0.07      0.07       143
           7       0.06      0.06      0.06       134
           8       0.05      0.05      0.05       138
           9       0.05      0.04      0.05       136
          10       0.08      0.09      0.08       138
          11       0.05      0.05      0.05       138

    accuracy                           0.07      1650
   macro avg       0.07      0.07      0.07      1650
weighted avg       0.07      0.07      0.07      1650

In [35]:
metrics.confusion_matrix(y_test, y_test_predicted)

array([[ 8, 12,  9,  7, 15,  7,  8, 11, 16, 10, 16, 11],
       [ 9, 14, 10, 12, 14, 12, 16, 18, 11,  7, 11,  9],
       [12, 31,  8,  7,  5, 14, 11,  8,  9,  7, 12, 12],
       [12, 16, 14, 10,  7, 13, 12, 13,  9,  8, 12, 10],
       [ 9, 14, 15, 14,  9, 11, 13,  8, 12, 10, 11, 10],
       [ 7, 14, 15, 12,  6, 17,  9, 15, 10,  6, 12, 19],
       [11, 16, 17,  7,  9,  9, 10, 11, 14, 15, 11, 13],
       [10, 16, 12,  9, 10, 13, 10,  8, 12, 14,  9, 11],
       [ 9, 18,  7, 15, 14, 14,  8, 12,  7,  8, 13, 13],
       [ 6,  8, 20,  6,  7,  9, 15, 12, 18,  6, 16, 13],
       [ 9, 15, 17, 14,  2,  6, 10, 12, 17, 11, 12, 13],
       [ 8, 15, 11, 10,  8, 21, 12, 16,  9, 11, 10,  7]])

In [156]:
number_of_estimators = np.arange(50, 150, 10)
number_of_estimators

max_depths = np.arange(5, 25, 2)
max_depths

optimal_number_of_estimators = number_of_estimators[0]
optimal_depth = max_depths[0]
optimal_accuracy = 0

for num in number_of_estimators:
    for depth in max_depths:
        model = xgboost.XGBClassifier(n_estimators=num, max_depth=depth, random_state=7)
        score = train_and_evaluate(model, x_train, y_train, x_val, y_val)
        
        if score > optimal_accuracy:
            optimal_accuracy = score
            optimal_number_of_estimators = num
            optimal_depth = depth

print(optimal_number_of_estimators, optimal_depth, optimal_accuracy)

50 19 0.11194029850746269

In [157]:
model = xgboost.XGBClassifier(n_estimators=optimal_number_of_estimators, max_depth=optimal_depth, random_state=7)

In [158]:
model.fit(x_trainval, y_trainval)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None,
              max_depth=np.int64(19), max_leaves=None, min_child_weight=None,
              missing=nan, monotone_constraints=None, multi_strategy=None,
              n_estimators=np.int64(50), n_jobs=None, num_parallel_tree=None, ...)

In [159]:
y_test_predicted = model.predict(x_test)
y_test_predicted

array([ 5,  7, 11, ...,  2,  2,  7], shape=(1650,))

In [160]:
model.score(x_train, y_train)

0.2171641791044776

In [161]:
model.score(x_test, y_test)

0.07696969696969697

In [162]:
print(metrics.classification_report(y_test, y_test_predicted))

              precision    recall  f1-score   support

           0       0.08      0.07      0.08       130
           1       0.09      0.10      0.10       143
           2       0.05      0.07      0.06       136
           3       0.09      0.09      0.09       136
           4       0.09      0.07      0.08       136
           5       0.09      0.10      0.10       142
           6       0.08      0.08      0.08       143
           7       0.07      0.07      0.07       134
           8       0.06      0.05      0.05       138
           9       0.06      0.05      0.05       136
          10       0.07      0.07      0.07       138
          11       0.09      0.09      0.09       138

    accuracy                           0.08      1650
   macro avg       0.08      0.08      0.08      1650
weighted avg       0.08      0.08      0.08      1650

In [163]:
metrics.confusion_matrix(y_test, y_test_predicted)

array([[ 9, 12, 13, 13,  9, 10, 13, 10, 13,  6, 14,  8],
       [ 8, 15, 14, 14,  8,  9, 10, 19, 13, 11, 12, 10],
       [ 9, 16, 10,  9, 11, 17, 14,  6, 11, 10, 14,  9],
       [10, 11, 15, 12, 12, 10, 16,  9,  6, 10, 15, 10],
       [ 9, 10, 24, 18, 10, 10, 10,  9, 10,  8, 11,  7],
       [ 6, 14, 13,  9, 11, 14,  8, 14,  8, 12, 15, 18],
       [11, 14, 19, 10,  9, 12, 12,  8, 10, 14, 14, 10],
       [ 7, 16, 15,  5,  9, 15, 13,  9,  7, 17,  8, 13],
       [13, 14, 13, 16,  9, 19,  9,  9,  7, 11,  6, 12],
       [ 8, 11, 18,  9,  7, 10, 15,  7, 14,  7, 13, 17],
       [12, 13, 17,  8,  5,  6, 14, 16, 14, 12, 10, 11],
       [ 6, 12, 12, 12, 12, 17,  9, 12, 12,  9, 13, 12]])